# fly.toml app configuration file generated for geo-ip-server-db on 2023-11-01T13:21:43+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "geo-ip-server-db"
primary_region = "ams"
kill_signal = "SIGTERM"
kill_timeout = "5m0s"

[experimental]
  enable_consul = true

[build]

[env]
  BACKEND_STORE = "consul"
  PRIMARY_REGION = "ams"

[[mounts]]
  source = "pg_data"
  destination = "/data"

[checks]
  [checks.pg]
    port = 5500
    type = "http"
    interval = "15s"
    timeout = "10s"
    grace_period = "30s"
    method = "get"
    path = "/flycheck/pg"
  [checks.role]
    port = 5500
    type = "http"
    interval = "15s"
    timeout = "10s"
    grace_period = "30s"
    method = "get"
    path = "/flycheck/role"
  [checks.vm]
    port = 5500
    type = "http"
    interval = "1m0s"
    timeout = "10s"
    grace_period = "1s"
    method = "get"
    path = "/flycheck/vm"

[[metrics]]
  port = 9187
  path = "/metrics"

[[vm]]
  size = "shared-cpu-1x"
  memory = "768mb"
